apiVersion: v1
kind: Service
metadata:
  labels:
    app: fnhttpac
  name: fnhttp-ac-svc
  namespace: iccv11
spec:
  ports:
  - port: 3198
    protocol: TCP
    targetPort: 3198
  selector:
    app: fnhttpac
  sessionAffinity: None
  type: NodePort
